// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

// For more information on how to use this file, see
// https://firebase.google.com/docs/build/multiproject

import { FirebaseOptions } from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
};
